import {StyleSheet} from 'react-native';
import DIMENSIONS from '../../Services/Constants/DIMENSIONS';
import COLOR from '../../Services/Constants/COLORS';

const styles = StyleSheet.create({
  appLogoSmall: {
    height: 70,
    marginTop: 30,
  },
  loginButton: {
    overflow: 'hidden',
    marginTop: 30,
  },
  signUpButton: {
    overflow: 'hidden',
    marginTop: 15,
    backgroundColor: COLOR.white,
  },
  choiceButtonContainer: {
    width: DIMENSIONS.screenWidth / 2,
    borderRadius: DIMENSIONS.borderRadius,
  },
  choiceButtonStyle: {
    width: DIMENSIONS.screenWidth / 2,
    borderRadius: DIMENSIONS.borderRadius,
  },
  buttonTitle: {
    color: COLOR.themeBlue,
  },
  buttonView: {
    marginTop: 15,
  },
  middleFlex: {
    justifyContent: 'center',
    flex: 5,
    alignItems: 'center',
  },
  googleView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  googleButton: {
    width: DIMENSIONS.bannerWidth,
    marginVertical: DIMENSIONS.sectionGap,
    height: 70,
  },
  haveAcc: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  blueBold: {
    fontWeight: 'bold',
    color: COLOR.themeBlue,
  },
  containerStyle: {
    borderWidth: 1,
    padding: 10,
    borderRadius: DIMENSIONS.borderRadiusXS,
    borderColor: COLOR.themeBlue,
  },
  signUpContainerStyle: {
    borderWidth: 1,
    paddingLeft: 40,
    borderRadius: DIMENSIONS.borderRadiusXS,
    borderColor: COLOR.themeBlue,
  },
  otpContainerStyle: {
    borderWidth: 1,
    padding: 10,
    borderColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    color: COLOR.black,
  },
  eyeIcon: {
    position: 'absolute',
    left: -40,
  },
  leftIcon: {
    position: 'absolute',
    left: '50%',
    top: '70%',
    transform: [{translateY: -12}],
  },
  roleDropDown: {
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderColor: COLOR.black,
    borderRadius: DIMENSIONS.borderRadius,
  },
  selectedTextStyle: {
    color: COLOR.black,
  },
  itemTextStyle: {
    color: COLOR.black,
  },
  dropdownText: {
    color: COLOR.black,
    fontSize: DIMENSIONS.textSize,
    textAlign: 'center',
  },
  imageContainerStyle: {
    borderWidth: 1,
    borderColor: COLOR.grey,
    borderRadius: DIMENSIONS.borderRadius,
    width: DIMENSIONS.iconCardBig,
    height: DIMENSIONS.iconCard,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginBottom: 20,
  },
  errorImageContainerStyle: {
    borderWidth: 1,
    borderColor: COLOR.red,
    borderRadius: DIMENSIONS.borderRadiusLarge,
    width: DIMENSIONS.iconXXXL,
    height: DIMENSIONS.iconXXXL,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    backgroundColor: COLOR.redOpacity,
  },
  imageSourceView: {
    width: DIMENSIONS.iconXXL,
    height: DIMENSIONS.iconXXL,
    borderRadius: DIMENSIONS.borderRadiusLarge,
  },
  inputContainerStyle: {
    borderColor: COLOR.transparent,
    marginBottom: 20,
  },
  loginHeader: {},
  loginImage: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    resizeMode: 'cover',
  },
  loginLogoView: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  loginLogo: {
    height: 200,
    width: 200,
    resizeMode: 'contain',
    marginBottom: 20,
  },
  changeOption: {
    fontWeight: 'bold',
    fontSize: DIMENSIONS.headerTextSize,
    padding: 10,
    paddingBottom: 10,
    color: COLOR.themeBlue,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    marginTop: 10,
  },
  loginText: {
    fontWeight: 'bold',
    fontSize: DIMENSIONS.largeText,
    textAlign: 'left',
    width: DIMENSIONS.bannerWidth,
    marginLeft: 10,
  },
  loginSubText: {
    fontWeight: 'bold',
    fontSize: DIMENSIONS.subtitleTextSize,
    color: COLOR.themeBlue,
    textAlign: 'left',
    width: DIMENSIONS.bannerWidth,
    marginVertical: 10,
  },
  authScreenView: {
    justifyContent: 'space-between',
    height: DIMENSIONS.screenHeight - 150,
  },
  loginAppName: {
    marginTop: DIMENSIONS.headerHeight,
  },
  loginName: {
    textAlign: 'left',
    marginLeft: 20,
    fontSize: DIMENSIONS.xxxlText,
    fontWeight: 'bold',
    color: COLOR.white,
    fontStyle: 'italic',
  },
  textLeft: {
    textAlign: 'left',
    marginLeft: 25,
    fontSize: DIMENSIONS.headerTextSize,
    fontWeight: '300',
    width: DIMENSIONS.bannerWidth,
  },
  boldKokan: {
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: DIMENSIONS.xxxlText,
    marginLeft: 25,
  },
  exploreText: {
    textAlign: 'left',
    fontSize: DIMENSIONS.xxlText,
    fontWeight: '300',
    marginLeft: 25,
  },
  appName: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.white,
    width: DIMENSIONS.appLogo + 40,
    height: DIMENSIONS.appLogo + 40,
    borderRadius: DIMENSIONS.borderRadiusXL,
    marginTop: 50,
    resizeMode: 'contain',
    shadowColor: COLOR.black,
    shadowOffset: {
      width: 10,
      height: 10,
    },
    elevation: 10,
  },
  appLogo: {
    height: DIMENSIONS.appLogo,
    width: DIMENSIONS.appLogo,
  },
  appNameText: {
    fontSize: DIMENSIONS.xlText,
    fontWeight: 'bold',
  },
  whiteText: {
    color: COLOR.white,
  },
  selectText: {
    color: COLOR.white,
    fontWeight: 'bold',
    top: 10,
  },
  choiceText: {
    marginVertical: 20,
    color: COLOR.themeBlue,
    fontWeight: '600',
  },
  sendOTPText: {
    fontWeight: '600',
  },
  addProfileView: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeText: {
    textAlign: 'left',
    fontWeight: '350',
    fontSize: DIMENSIONS.xxlText,
    marginLeft: 25,
    marginTop: 50,
  },
  dropdown: {
    width: DIMENSIONS.bannerWidth,
    height: 46,
    borderWidth: 1,
    borderColor: COLOR.themeBlue,
    borderRadius: DIMENSIONS.borderRadiusXS,
    marginTop: 15,
    paddingLeft: 10,
  },
  dropdownIcon: {
    width: 30,
    height: 30,
  },
  langButtonStyle: {
    width: DIMENSIONS.bannerWidth / 3,
    backgroundColor: COLOR.themeBlue,
    borderRadius: DIMENSIONS.borderRadiusXS,
    marginTop: 20,
  },
  buttonTitleStyle: {
    color: COLOR.white,
    fontWeight: 'bold',
  },
  root: {flex: 1, padding: 20},
  title: {textAlign: 'center', fontSize: 30},
  codeFieldRoot: {marginTop: 20},
  cell: {
    height: 50,
    width: 40,
    margin: 10,
    backgroundColor: COLOR.white,
    borderWidth: 1,
    borderColor: COLOR.themeBlue,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 45,
    color: COLOR.themeBlue,
    borderRadius: DIMENSIONS.borderRadiusXS,
  },
  focusCell: {
    borderColor: COLOR.themeBlue,
  },
  middleFlexImage: {
    justifyContent: 'center',
    padding: 10,
    flex: 5,
    alignItems: 'center',
  },
  lottie: {
    width: 300,
    height: 300,
  },
  // New Ocean Theme Styles
  oceanContainer: {
    flex: 1,
    backgroundColor: '#0D3D4A', // Ocean Deep
    justifyContent: 'space-between',
  },
  sunBackground: {
    position: 'absolute',
    top: '15%',
    alignSelf: 'center',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(242, 217, 139, 0.4)', // Sand Light transparent
    justifyContent: 'center',
    alignItems: 'center',
  },
  sunInner: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#F2D98B', // Sand Light
    shadowColor: '#C4972A',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: 80,
    zIndex: 2,
  },
  logoCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 3,
    borderColor: '#C4972A', // Sand Mid
    backgroundColor: '#0D3D4A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    elevation: 5,
  },
  logoTextSmall: {
    color: '#B8E4EA', // Ocean Foam
    fontSize: 10,
    letterSpacing: 2,
    marginBottom: 5,
  },
  logoTextMain: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    fontFamily: 'serif',
  },
  taglineText: {
    color: '#F2D98B', // Sand Light
    fontSize: 12,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: 10,
    fontWeight: '500',
  },
  mainAppName: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'serif',
    marginBottom: 5,
  },
  subTagline: {
    fontSize: 16,
    fontStyle: 'italic',
    color: COLOR.themeBlue,
    opacity: 0.9,
  },
  loginSection: {
    width: '100%',
    paddingHorizontal: 30,
    backgroundColor: 'transparent',
    zIndex: 2,
  },
  authContentContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 250,
  },
  loginTitle: {
    fontSize: 20,
    color: COLOR.black,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: 'serif',
  },
  customGoogleBtn: {
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    height: 55,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  googleBtnText: {
    color: '#1C1917',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLOR.grey,
  },
  dividerText: {
    color: COLOR.greyDark,
    marginHorizontal: 16,
    fontSize: 12,
  },
  guestBtn: {
    backgroundColor: COLOR.white,
    borderRadius: 50,
    height: 55,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: COLOR.themeBlue,
  },
  guestBtnText: {
    color: COLOR.themeBlue,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },
  featuresContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginTop: 28,
  },
  featureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(88, 147, 216, 0.1)',
    borderRadius: 50,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLOR.themeBlue,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  featureText: {
    color: COLOR.themeBlue,
    fontSize: 11,
    fontWeight: '500',
    marginLeft: 6,
  },
  footerTextContainer: {
    marginTop: 24,
    alignItems: 'center',
  },
  footerText: {
    color: COLOR.greyDark,
    fontSize: 12,
    textAlign: 'center',
    opacity: 0.7,
    lineHeight: 18,
  },
  footerLink: {
    color: COLOR.themeBlue,
    fontWeight: 'bold',
  },
  waveContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '40%',
    zIndex: 1,
    opacity: 0.3,
    backgroundColor: '#1B6B7B', // Ocean Mid
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    transform: [{scaleX: 1.5}],
  },
});

export default styles;
