import COLOR from '../../Services/Constants/COLORS';
import DIMENSIONS from '../../Services/Constants/DIMENSIONS';

const {StyleSheet} = require('react-native');

const styles = StyleSheet.create({
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexRowLike: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  flexColumn: {
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  placeContainer: {
    alignSelf: 'center',
    // flex: 1,
    flexDirection: 'row',
    width: DIMENSIONS.bannerWidth,
    maxHeight: DIMENSIONS.halfWidth - 50,
    minHeight: DIMENSIONS.halfWidth - 50,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    elevation: 10,
    marginVertical: 10,
    marginHorizontal: 10,
  },
  placeImageView: {
    flex: 2,
  },
  likeView: {
    marginRight: 5,
  },
  placeImageStyle: {
    borderTopLeftRadius: DIMENSIONS.borderRadius,
    borderBottomLeftRadius: DIMENSIONS.borderRadius,
  },
  placeContentView: {
    flex: 3,
    padding: 10,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  placeContentTop: {
    flex: 1,
    justifyContent: 'space-between',
    paddingBottom: 10,
  },
  placeName: {
    fontSize: DIMENSIONS.headerTextSize,
    fontWeight: 'bold',
    color: COLOR.black,
    textAlign: 'left',
  },
  placeTag: {
    fontSize: DIMENSIONS.subtitleTextSize,
    fontWeight: 600,
  },
  starStyle: {
    width: 2,
    color: COLOR.yellow,
  },
  placeMetaView: {
    paddingTop: 10,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderColor: COLOR.grey,
    borderStyle: 'dashed',
  },
  vertDivider: {
    borderWidth: 1,
    marginHorizontal: 5,
    borderColor: COLOR.grey,
  },
  splitView: {
    padding: 5,
    flexWrap: 'wrap',
  },
  lightBlackText: {
    color: COLOR.lightBlack,
  },
  catCardContainer: {
    justifyContent: 'space-evenly',
    margin: 10,
    flexDirection: 'row',
  },
  catCardIcon: {
    width: DIMENSIONS.bannerWidth / 4,
    height: DIMENSIONS.bannerWidth / 4,
  },
  projectCard: {
    minHeight: DIMENSIONS.bannerHeight,
    maxHeight: DIMENSIONS.bannerHeight,
    width: DIMENSIONS.bannerWidth,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLOR.grey,
    marginVertical: 10,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLOR.black,
  },
  projectImage: {
    height: DIMENSIONS.bannerHeight - 30,
  },
  projectImageStyle: {
    opacity: 0.7,
  },
  routeHeadCardSkeleton: {
    height: DIMENSIONS.bannerHeight / 2 + 32,
    width: DIMENSIONS.bannerWidth,
    alignSelf: 'center',
    elevation: 10,
    zIndex: 10,
    borderRadius: DIMENSIONS.borderRadiusXS,
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  routeHeadCard: {
    height: DIMENSIONS.bannerHeight / 2 + 32,
    // height: "auto",
    width: DIMENSIONS.bannerWidth,
    backgroundColor: COLOR.white,
    alignSelf: 'center',
    elevation: 10,
    borderRadius: DIMENSIONS.borderRadiusXS,
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  routeHeadCardTitle: {
    fontWeight: 'bold',
    lineHeight: 20,
    fontSize: DIMENSIONS.subtitleTextSize,
    textAlign: 'left',
  },
  routeHeadCardBottom: {
    borderBottomLeftRadius: DIMENSIONS.borderRadiusXS,
    borderBottomRightRadius: DIMENSIONS.borderRadiusXS,
    alignItems: 'center',
    paddingVertical: 4,
  },
  busImage: {
    height: DIMENSIONS.iconXXL,
    width: DIMENSIONS.iconXXL,
  },
  routeHeadCardImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cityCardSkeleton: {
    width: DIMENSIONS.bannerWidth,
    height: DIMENSIONS.bannerWidth + 20,
    borderRadius: DIMENSIONS.borderRadius,
    elevation: 10,
    margin: 10,
  },
  placeCardSkeleton: {
    width: DIMENSIONS.halfWidth - 50,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadiusSmall,
    height: DIMENSIONS.headerHeight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    elevation: 5,
    alignSelf: 'stretch',
    marginHorizontal: 10,
  },
  cityCard: {
    width: DIMENSIONS.bannerWidth,
    height: DIMENSIONS.bannerWidth + 20,
    elevation: 10,
    margin: 10,
    padding: 10,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'space-evenly',
  },
  subCatCard: {
    width: DIMENSIONS.iconCard,
    height: DIMENSIONS.iconCard,
    padding: 10,
    margin: 1,
    backgroundColor: COLOR.white,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  subCatCard1: {
    width: DIMENSIONS.iconCard,
    height: DIMENSIONS.iconCard,
    elevation: 10,
    margin: 10,
    padding: 10,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'center',
  },
  placeCard: {
    width: DIMENSIONS.bannerWidth,
    height: DIMENSIONS.bannerHeight + 100,
    elevation: 10,
    margin: 10,
    marginBottom: 30,
    padding: 10,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'space-evenly',
  },
  cityOverlay: {
    ...StyleSheet.absoluteFillObject,
    // backgroundColor: COLOR.black,
    borderRadius: DIMENSIONS.borderRadius,
    height: DIMENSIONS.bannerWidth / 1.19,
  },
  cityLikeView: {
    backgroundColor: COLOR.white,
    height: 35,
    width: 35,
    borderRadius: DIMENSIONS.borderRadius,
    right: 5,
    top: 0,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  commentCount: {
    borderRadius: DIMENSIONS.borderRadius,
    zIndex: 10,
    fontWeight: 'bold',
    backgroundColor: COLOR.themeBlue,
    color: COLOR.white,
    paddingHorizontal: 7,
    paddingVertical: 2,
    left: 13,
    top: -7,
    position: 'absolute',
  },
  avgRating: {
    borderRadius: DIMENSIONS.borderRadiusLarge,
    zIndex: 10,
    position: 'absolute',
    padding: 2,
    fontWeight: 'bold',
  },
  cityStarView: {
    backgroundColor: COLOR.white,
    height: 35,
    width: 100,
    left: 10,
    top: 10,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeStarView: {
    backgroundColor: COLOR.white,
    height: 35,
    width: 100,
    left: 10,
    top: -20,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cityImage: {
    width: DIMENSIONS.bannerWidth,
    position: 'absolute',
  },
  placeImage: {
    width: DIMENSIONS.halfWidth - 60,
    maxHeight: DIMENSIONS.halfWidth - 50,
    minHeight: DIMENSIONS.halfWidth - 50,
    position: 'absolute',
  },
  cityImageStyle: {
    borderRadius: DIMENSIONS.borderRadius,
    height: DIMENSIONS.bannerWidth / 1.19,
  },
  cityDetailsOverlay: {
    width: DIMENSIONS.bannerWidth - 40,
    height: 'auto',
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    padding: 15,
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
    textAlign: 'left',
  },
  placeDetailsOverlay: {
    width: DIMENSIONS.bannerWidth - 40,
    height: 'auto',
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    padding: 15,
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  cityName: {
    fontSize: DIMENSIONS.headerTextSize,
    fontWeight: 'bold',
  },
  boldText: {
    fontWeight: 'bold',
    textAlign: 'left',
  },
  boldTextLong: {
    fontWeight: 'bold',
    textAlign: 'right',
    maxWidth: 200,
  },
  greyText: {
    color: COLOR.greyDark,
    textAlign: 'left',
    width: DIMENSIONS.halfWidth - 90,
    fontSize: DIMENSIONS.textSize,
  },
  greyTextLong: {
    color: COLOR.greyDark,
  },
  cityCardSmall: {
    width: DIMENSIONS.bannerWidth / 2,
    height: DIMENSIONS.bannerHeight + 90,
    elevation: 10,
    marginVertical: 10,
    marginBottom: 25,
    marginHorizontal: 5,
    padding: 10,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'space-between',
  },
  citySmallImage: {
    width: DIMENSIONS.bannerWidth / 2,
    minHeight: DIMENSIONS.bannerHeight + 190,
    position: 'absolute',
  },
  citySmallDetailsOverlay: {
    width: DIMENSIONS.bannerWidth / 2 - 30,
    height: 110,
    backgroundColor: COLOR.white,
    borderRadius: DIMENSIONS.borderRadiusSmall,
    padding: 10,
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: -20,
    textAlign: 'left',
  },
  packageLikeView: {
    position: 'absolute',
    right: 5,
    top: 10,
  },
  citySmallLikeView: {
    backgroundColor: COLOR.white,
    height: 30,
    width: 30,
    borderRadius: DIMENSIONS.borderRadius,
    right: 5,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 13,
  },
  citySmallName: {
    fontSize: DIMENSIONS.textSize,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  citySmallTagLine: {
    fontSize: DIMENSIONS.textSizeSmall,
    textAlign: 'left',
  },
  citySmallStarView: {
    backgroundColor: COLOR.white,
    height: 30,
    width: 80,
    left: 10,
    borderRadius: DIMENSIONS.borderRadius,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  cityCardSmallSkeleton: {
    width: DIMENSIONS.bannerWidth / 2,
    height: DIMENSIONS.bannerHeight + 90,
    borderRadius: DIMENSIONS.borderRadius,
    elevation: 10,
    margin: 10,
  },
  routeCardIcons: {
    marginRight: 3,
  },
  packageCardSmall: {
    margin: 5,
    elevation: 10,
    backgroundColor: COLOR.white,
    padding: 5,
    borderRadius: DIMENSIONS.borderRadiusSmall,
    height: DIMENSIONS.halfWidth + 65,
    width: DIMENSIONS.halfWidth - 30,
    // alignItems: "center",
    display: 'flex',
    flexDirection: 'column',
  },
  packageCardLong: {
    marginVertical: 5,
    marginHorizontal: 10,
    elevation: 10,
    backgroundColor: COLOR.white,
    padding: 5,
    borderRadius: DIMENSIONS.borderRadiusXS,
    height: DIMENSIONS.halfWidth - 60,
    width: DIMENSIONS.screenWidth - 30,
    // alignItems: "center",
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  smallPackageImage: {
    width: DIMENSIONS.halfWidth - 40,
    height: DIMENSIONS.halfWidth - 40,
  },
  smallPackageImageStyle: {
    width: DIMENSIONS.halfWidth - 40,
    height: DIMENSIONS.halfWidth - 40,
    borderTopLeftRadius: DIMENSIONS.borderRadiusSmall,
    borderTopRightRadius: DIMENSIONS.borderRadiusSmall,
    borderBottomLeftRadius: DIMENSIONS.borderRadiusXS,
    borderBottomRightRadius: DIMENSIONS.borderRadiusXS,
  },
  smallPackageImageLong: {
    width: DIMENSIONS.halfWidth - 60,
    height: DIMENSIONS.halfWidth - 70,
  },
  smallPackageImageLongStyle: {
    width: DIMENSIONS.halfWidth - 60,
    height: DIMENSIONS.halfWidth - 70,
    borderRadius: DIMENSIONS.borderRadiusXS,
  },
  packageCardContent: {
    width: DIMENSIONS.halfWidth - 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
    textAlign: 'left',
    alignItems: 'flex-start',
  },
  packageCardContentLong: {
    flexDirection: 'column',
    marginTop: 5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  flexRowSmall: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexRowSmallLong: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  lastContent: {
    top: 2
  },
  lastContentLong: {
    alignSelf: 'flex-end',
  },
});

export default styles;
