const STRING = {
  APPNAME: 'Tourkokan',
  EXPLORE: 'Explore the Enchanting',
  KOKAN: 'KOKAN',
  COMPANION: "Your Ultimate Travel Companion for Maharashtra's Coastal Gem.",
  WELCOME: 'Welcome to',

  BUTTON: {
    YES: 'Yes',
    NO: 'No',
    OK: 'Ok',
    CANCEL: 'Cancel',
    ACCEPT: 'Accept',
    SEARCH: 'Search',
    SUBMIT: 'Submit',
    SEE_MORE: 'See More',
    SEE_ALL: 'See All',
    READ_MORE: 'Read More',
    READ_LESS: 'Read Less',
    CHOOSE_PLAN: 'Choose Plan',
    UPDATE: 'Update',
    EDIT_PROFILE: 'Edit Profile',
    UPDATE_LOCATION: 'Update Location',
    HOME_LOCATION: 'Home Location',
    CURRENT_LOCATION: 'Current Location',
    LOGIN: 'Login',
    SIGNUP: 'Sign Up',
    SEND_OTP: 'Send OTP',
    GENERATE_OTP: 'Generate OTP',
    LOGIN_WITH_PASSWORD: 'Login with Password',
    LOGIN_WITH_OTP: 'Login with OTP',
    REGISTER: 'Register',
    VERIFY: 'Verify & Login',
    CLICK_TO_UPDATE: 'Click to Update',
    LOGOUT: 'Logout  ',
    SEE_CITIES: 'See all Cities',
    OTP: 'OTP',
    PASSWORD: 'Password',
    CONTINUE: 'Continue',
    LOGINOTP: 'Login with OTP',
    LOGINPASS: 'Login with Password',
    NEXT: 'Next',
    ADD_PHOTO: 'Add Profile Photo',
    VIEW_MAP: 'View on Map',
    SEND: 'Send',
    SAVE: 'Save',
    ATTACHMENT: '+ Upload Attachment',
    ONLINE: 'Online',
    OFFLINE: 'Offline',
    ONLINE_MODE: 'Online Mode',
    OFFLINE_MODE: 'Offline Mode',
    LOCATION: 'Location',
    ADD_QUERY: 'Add Query',
    CONTACT: 'Contact',
  },
  SCREEN: {
    ROOT: 'Root',
    HOME: 'Home',
    PRICING: 'Pricing',
    REQUEST_PAID_ADVERTISEMENT: 'Request Paid Advertisement',
    CONTACT_US: 'Contact Us',
    EMERGENCY: 'Emergency',
    WEATHER: 'Weather',
    PROFILE: 'Profile',
    PROFILE_VIEW: 'ProfileView',
    BUS_TIMINGS: 'BusTimings',
    CATEGORY_PROJECTS: 'CategoryProjects',
    CATEGORIES: 'Categories',
    EXPLORE: 'Explore',
    EXPLOREGRID: 'ExploreGrid',
    MAP_SCREEN: 'MapScreen',
    CITIES: 'Cities',
    ROUTES: 'Routes',
    PLACES: 'Places',
    MAP: 'Map',

    LANG_SELECTION: 'LangSelection',
    AUTH_SCREEN: 'AuthScreen',
    LOGIN: 'Login',
    SIGN_UP: 'SignUp',
    EMAIL_SIGN_IN: 'EmailSignIn',
    EMAIL: 'Email',
    VERIFY_OTP: 'VerifyOTP',
    PASSWORD_LOGIN: 'PasswordLogin',

    SEARCH: 'Search',
    SEARCH_PLACE: 'SearchPlace',
    CITY_PLACE_SEARCH: 'CityPlaceSearch',

    ROUTES_LIST: 'RoutesList',
    SEARCH_LIST: 'SearchList',
    ALL_ROUTES_SEARCH: 'AllRoutesSearch',
    ROUTES_LIST: 'RoutesList',
    CITY_LIST: 'CityList',
    PROJECT_LIST: 'ProjectList',
    QUERIES_LIST: 'QueriesList',
    STOP_LIST: 'StopList',

    PLACE_DETAILS: 'PlaceDetails',
    PROJECT_DETAILS: 'ProjectDetails',
    STOP_DETAILS: 'StopDetails',
    CITY_DETAILS: 'CityDetails',
    GALLERY: 'Gallery',
  },
  STORAGE: {
    ACCESS_TOKEN: 'access_token',
    ADDRESS: 'address',
    USER_ID: 'userId',
    USER_EMAIL: 'userEmail',
    USER_NAME: 'userName',
    IS_FIRST_TIME: 'isFirstTime',
    API_TOKEN: 'apiToken',
    LANDING_RESPONSE: 'landingResponse',
    PROFILE_RESPONSE: 'profileResponse',
    CITIES_RESPONSE: 'citiesResponse',
    PLACES_RESPONSE: 'placesResponse',
    ROUTES_RESPONSE: 'routesResponse',
    EXPLORE_CITIES_RESPONSE: 'exploreCitiesResponse',
    CATEGORIES_RESPONSE: 'categoriesResponse',
    EMERGENCY: 'emergency',
    QUERIES: 'queries',
    GALLERY: 'gallery',
    MODE: 'mode',
    SELECTED_CITY_ID: 'selectedCityId',
    SELECTED_CITY_NAME: 'selectedCityName',
    LANGUAGE: 'language',
    REFERRAL_CODE: 'referralCode',
    CURRENT_LATITUDE: 'currentLatitude',
    CURRENT_LONGITUDE: 'currentLongitude',
    TERMS_ACCEPTED: 'termsAccepted',
  },
  HEADER: {
    BUS_TIMINGS: 'Bus Timings',
    CONTACT_US: 'Contact Us',
    EMERGENCY: 'Emergency',
    PRICING: 'Pricing',
    VERIFY_OTP: 'Verify OTP',
    CITY: 'City',
    PLACE: 'Place',
    CITIES: 'Cities',
    EXPLORE: 'Explore',
    PLACE_CATEGORIES: 'Place Categories',
    PROJECTS: 'Projects',
    ROUTE: 'Route',
    ROUTES: 'Routes',
    STOPS: 'Stops',
    COMMENTS: 'Comments',
    SUBCATEGORIES: 'sub-categories',
    CLASSIFICATIONS: 'Classifications',
  },
  ALERT: {
    FAILED: 'Failed',
    WENT_WRONG: 'Something went wrong...',
    OTP_SENT: 'OTP is sent on your email, verify otp to register!',
    REGI_SUCCESS: 'Registration Successful, now login to continue...',
    SOURCE_DESTINATION_REQUIRED: 'Source & Destination are required..!',
    ADDING_SOON: 'We are adding new places inside this category soon..!',
    LOADING: 'Loading...',
    ERROR_CURRENT_LOCATION: 'Error getting current location: ',
    FETCHING_TEXT: 'We are getting your location please wait',
    LOGOUT_ALERT: 'Do you real want to Logout?',
    INVALID_EMAIL: 'Please enter valid email',
    INVALID_PASSWORD: 'Invalid password pattern',
    REQUIRED_FIELDS: 'All fields are required',
    INVALID_MOBILE: 'Invalid mobile number',
    PLEASE_ENTER_NAME: 'Please enter valid name',
    PLEASE_ENTER_VALID_EMAIL: 'Please enter valid email',
    PLEASE_ENTER_VALID_MOBILE: 'Please enter valid mobile number',
    PLEASE_ENTER_VALID_REFERRAL: 'Please enter valid Referral code',
    PLEASE_ACCEPT_PRIVACY: 'Please accept privacy policy',
    LOCATION_SERVICES_DISABLED: 'Please enable your loaction from settings',
    LOCATION_REQUIRED: 'Location Required',
    ENABLE_LOCATION_SERVICES:
      'Please enable location services to continue using this app.',
    OPEN_SETTINGS: 'Open Settings',
    MODE_OFFLINE:
      'The mode is set to offline; please switch to online to proceed.',
    NO_INTERNET_AVAILABLE_MODE_ONLINE:
      'No internet connection available, but the mode is set to online. Please check your network.',
    INTERNET_AVAILABLE_MODE_OFFLINE:
      'Internet is available, but mode is set to offline, Please check your mode.',
    NETWORK: 'No internet connection available.',
    THANK_YOU: 'Thank You',
    VISIT_AGAIN: 'Thank you for using the Tourkokan...!  Please visit again...',
    TNC: 'Please accept the Terms and Conditions.',
    SHARE_LOCATION: 'Please share your location.',
    LOC_ENABLED: 'Location services are already enabled',
    LOCATION_ENABLED: 'Location services have been enabled',
    LOC_ERROR: 'Error enabling location services:',
    LOC_FAILED: 'Failed to enable location services',
    LOC_ENABLE: 'Location Enabled',
    ENABLE_LOC: 'Enable Location',
    SELECT_LANG: 'Select Language',
    ENTER_REFERRAL: 'Enter Referral Code',
    ACCEPT_TERMS: 'Accept Terms and Conditions',
    SELECT_MODE: 'Select Online/Offline Mode',
    PLEASE_CONTACT:
      'Data may not be perfect. If you find any false/wrong data here, please Contact Us by clicking on top corner. Arrival timings will be added soon.',
  },
  TABLE: {
    CITY: 'City',
    PLACE: 'Place',
    CITIES: 'cities',
    PLACES: 'places',
    SITES: 'Sites',
    SITE: 'Site',
  },
  CITY: {
    SINDHUDURG: 'Sindhudurg',
    DEVGAD: 'Devgad',
    KANKAVLI: 'Kankavli',
    MAHARASHTRA: 'Maharashtra',
  },
  TYPE: {
    TEXT: 'text',
    PASSWORD: 'password',
    NUM: 'num',
    PHONE: 'phone',
    EMAIL: 'email',
    PHOTO: 'photo',
    DROP_DWN: 'dropDwn',
  },
  PLACEHOLDER: {
    ENTER_TEXT: 'Enter Text',
    ENTER_OTP: 'Enter OTP',
    MOBILE_NUMBER: 'Mobile Number',
    SEARCH_SOURCE: 'Search Source Stop',
    SEARCH_DESTINATION: 'Search Destination Stop',
    SEARCH_CITY_PLACE: 'Search for city, place',
  },
  LABEL: {
    SOURCE: 'Source',
    DESTINATION: 'Destination',
    MOBILE: 'Mobile',
    MOBILE_NO: 'Mobile Number (optional)',
    PASSWORD: 'Password',
    SET_PASSWORD: 'Set Password',
    EMAIL: 'Email',
    REFERRAL: 'Referral',
    REFERRAL_CODE: 'Referral Code (optional)',
    EMAIL_ID: 'Email ID',
    NAME: 'Name',
    OTP: 'OTP',
    CONFIRM_PASSWORD: 'Confirm Password',
    CITY_NAME: 'City Name',
    MESSAGE: 'Message',
    COMMENT: 'Comment',
    TITLE: 'Title',
    DESCRIPTION: 'Description',
    SIGN_IN: ' Sign In',
    SIGN_UP: ' Sign Up',
    LOG_IN: 'Login',
  },
  EVENT: {
    HARDWARE_BACK_PRESS: 'hardwareBackPress',
    FOCUS: 'focus',
  },
  CHIPS: {
    LANGUAGE: 'Language',
    UPDATE_LOCATION: 'Update Location',
    UPDATE_PROFILE: 'Update Profile',
    SETTINGS: 'Settings',
    LOGOUT: 'Logout',
    CHANGE_LANGUAGE: 'Change Language',
    SELECT_LANGUAGE: 'Select Language',
  },
  ICON: {
    NAME: 'user',
    EMAIL: 'mail',
    MOBILE_NO: 'phone-call',
    HASH: 'hash',
  },
  POLICY: {},

  PRESS_BACK: 'Press back again to exit',
  OTP_VERIFICATION: 'OTP Verification',
  WE_HAVE_SENT: 'We have sent an OTP to verify your email.',
  SENT_TO: 'Sent to ',
  RESEND_WITHIN: 'You can resend your OTP within (00:_)',
  DIDNT_RECEIVE: "Haven't received OTP yet? ",
  HAVE_ACC: 'Already have an Account? ',
  TAKEN: 'already been taken',
  DONT_HAVE_ACC: "Don't have an Account? ",
  SIGN_IN: ' Sign In',
  SIGN_UP: ' Sign Up',
  RESEND: 'Resend OTP',
  SEND_OTP: 'Send OTP',
  COMING_SOON: 'Coming Soon...',
  UN_RESERVED: 'Un Reserved',
  STOPS: 'Stops',
  KM: 'km',
  LOCATION_ACCESS_REQUIRED: 'Location Access Required',
  NEEDS_TO_ACCESS: 'This App needs to Access your location',
  PERMISSION_DENIED: 'Permission Denied',
  GETTING_LOCATION: 'Getting Location ...',
  YOU_ARE_HERE: 'You are Here',
  GRANTED: 'granted',
  SEARCH_FOR_AREA: 'Search for area, street name...',
  USE_CURRENT_LOCATION: 'Use Current Location',
  RECENT_LOCATION: 'Recent Location',
  OR: '---------- OR ----------',
  ROLE: 'Role',
  SELECT_ROLE: 'Select Role',
  TO_EXPLORE: 'Lot more to Explore...',
  TEST_MARKER: 'Test Marker',
  MARKER_DESCRIPTION: 'This is a description of the marker',
  ETA: 'ETA: ',
  ETD: 'ETD: ',
  NO_ROUTES: 'No Routes Available',
  SET_LOCATION: 'Set Your Primary Location',
  NETWORK: 'Network Error',
  NO_INTERNET:
    'Please check your connectivity... Once data is synced you can use offline.',
  NO_INTERNET_MAP:
    'Please check your connectivity... Internet connection is mandatory to load Map.',
  GET_MORE_DATA: 'Please connect to internet to get more data.',
  LOADER_TEXT: 'Picking Up Your Data...',
  ADDED: 'More details will be added soon...',
  NO_COMMENTS: 'No comments yet',
  START_CONVO: 'Start Conversation',
  NO_DATA: 'No data available at this instance.',
  SELECT_OPTION: 'Select Login Option',
  LOG_IN: 'Login',
  LOG_IN_SUB: 'Enter your email and choose a login option to continue.',
  CHANGE: 'Click to Change Option',
  PLEASE_FILL: 'Please fill all the details to Register.',
  ACCEPT_POLICY: 'Please accept Privacy Policy to Register.',
  UNCOVER: 'Enter your start and end points to uncover the best routes.',
  LOCATION: 'Location',
  ADDRESS: 'User Address',
  CONNECT: "Connect with Us: We're Here to Listen",
  ROUTES: 'Routes',
  VILLAGES: 'Villages',
  ACCEPT_TNC: 'I Accept Terms & Conditions & Privacy Policy',
  APP_USAGE: 'How would you like to use your app?',
  NOTE: 'Please note: Even in offline mode, a network connection is required initially to complete the login process and load essential data.',
  REFER_EARN:
    'Friends don’t let friends travel unprepared—refer them to TourKokan and get rewarded for every new journey started!',
};

export default STRING;
